packages:
  - 'packages/*'
  - 'examples/*'
  - 'examples/.interop/*'
  - 'examples/.test/*'
  - 'examples/minimal/*'
  - 'examples/minimal-react/*'
  - 'examples/quickstart/*'
  - 'www'
  - 'www/og-image'
